CREATE TABLE timetracker ( 
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	name VARCHAR(20)DEFAULT '', 
	element SMALLINT(1) UNSIGNED DEFAULT 0,
	num_element SMALLINT(1) UNSIGNED DEFAULT 0,  
	date DATE );

CREATE TABLE timetracker_element ( 
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	element VARCHAR(20) DEFAULT '', 
	priority TINYINT(1) UNSIGNED DEFAULT 0,
	date DATE ); 
