#!perl

=head1 NAME

  Timetracker

=cut

our ($html, %FORM, $db, %conf, $admin, %lang);

use Timetracker::db::Timetracker;
my $Timetracker = Timetracker->new($db, $admin, \%conf);
use Admins;
my $Admins = Admins->new($db, \%conf);

use Data::Dumper;
use strict;

#**********************************************************

=head2 timetracker() - Accounting and time allocation. Report.

=cut

#**********************************************************

sub timetracker {

  reports({ DATE => $FORM{FROM_DATE_TO_DATE}, PERIOD_FORM => 1, NO_GROUP => 1, NO_TAGS => 1, DATE_RANGE => 1 });

  my %hash                     = ();
  my @element                  = ();
  my $Timetracker_list         = $Timetracker->list_for_timetracker({ COLS_NAME => 1, DATE => $FORM{FROM_DATE_TO_DATE} });
  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1 });
  my $Admin_name;
  my @priority = ();

  foreach my $element (@$Timetracker_list_element) {

    push @element, $element->{element};

    if ($element->{priority} == 1) {
      push @priority, $element->{element};
    }

    foreach my $item (@$Timetracker_list) {

      $Admin_name = $Admins->info($item->{aid});

      if ($element->{id} == $item->{element_id}) {

        $hash{ $Admin_name->{A_FIO} }->{ $element->{element} } += $item->{time_per_element};
      }
      else {
        $hash{ $Admin_name->{A_FIO} }->{ $element->{element} } += 0;
      }
    }
  }

  my $table = $html->table(
    {
      width   => "100%",
      caption => $lang{TIMETRACKER},
      title   => [ $lang{NAME}, @element, $lang{COEFFICIENT} ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      MENU    => "$lang{ADD}:index=" . get_function_index('add_time') . "&add_form=1&$pages_qs:add",
      export  => 1,
    }
  );

  my $coefficient;
  my @num_element;
  my $sum_num_element;

  foreach my $name (sort keys %hash) {

    @num_element     = ();
    $coefficient     = 0;
    $sum_num_element = 0;

    foreach my $item (@element) {
      $sum_num_element += $hash{$name}->{$item};
      push @num_element, ($hash{$name}->{$item} || 0);
      foreach my $element (@priority) {
        if ($element eq $item) {
          $coefficient += $hash{$name}->{$item};
        }
      }
    }

    $coefficient = ($coefficient) ? sprintf('%0.1f', (($coefficient * 100) / $sum_num_element)) : 0;
    $table->addrow($name, @num_element, "$coefficient");
  }

  print $table->show();

}

#**********************************************************

=head2 add_time() - Filling out a report.

=cut

#**********************************************************

sub add_time {

  my $date_for_picker = $DATE;
  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1 });
  my $form_group;
  my @element;
  my @num_element;
  my @element_id;
  my %hash;
  my $btn_action = 'ADD';
  my $btn_value  = $lang{ADD};
  my %hash1;

  if ($FORM{ADD}) {

    $Timetracker->del(
      {
        AID  => $admin->{AID},
        DATE => $FORM{DATE},
      }
    );

    foreach my $element (@$Timetracker_list_element) {

      $Timetracker->add(
        {
          AID              => $admin->{AID},
          ELEMENT_ID       => $element->{id},
          TIME_PER_ELEMENT => $FORM{ $element->{id} },
          DATE             => $FORM{DATE},
        }
      );

    }

    $html->message("info", $lang{ADD_MASSAGE}, $lang{OPERATION});
    $date_for_picker = $FORM{DATE};
  }

  if ($FORM{DELETE}) {

    $Timetracker->del(
      {
        AID  => $admin->{AID},
        DATE => $FORM{DELETE},
      }
    );

    $html->message("info", $lang{DELETE_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{CHANGE}) {

    $Timetracker->del(
      {
        AID  => $admin->{AID},
        DATE => $FORM{DATE},
      }
    );

    foreach my $element (@$Timetracker_list_element) {

      $Timetracker->add(
        {
          AID              => $admin->{AID},
          ELEMENT_ID       => $element->{id},
          TIME_PER_ELEMENT => $FORM{ $element->{id} },
          DATE             => $FORM{DATE},
        }
      );
    }

    $html->message("info", $lang{CHANGE_MASSAGE}, $lang{OPERATION});
  }

  my $Timetracker_list = $Timetracker->list_for_timetracker(
    {
      COLS_NAME => 1,
      DATE      => $FORM{FROM_DATE_TO_DATE},
      DESC      => "desc",
      AID       => $admin->{AID}
    }
  );

  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1, DESC => "desc" });

  if($Timetracker->{errno}){
    $html->message("err", $lang{ERROR}, $lang{NOTABLES});
    return 1;
  }

  if ($FORM{EDIT}) {
    $btn_action      = 'CHANGE';
    $btn_value       = $lang{CHANGE};
    $date_for_picker = $FORM{EDIT};
    foreach my $element (@$Timetracker_list_element) {

      foreach my $item (@$Timetracker_list) {

        if ($item->{aid} eq $FORM{NAME} && $item->{date} eq $FORM{EDIT}) {

          $hash1{ $item->{element_id} } = $item->{time_per_element};
        }
      }
    }
  }

  foreach my $element (@$Timetracker_list_element) {

    $form_group .= $html->tpl_show(
      _include("timetracker_add_form_group", "Timetracker"),
      {
        ELEMENT     => $element->{element},
        ID          => $element->{id},
        NUM_ELEMENT => $hash1{ $element->{id} }
      },
      { OUTPUT2RETURN => 1 }
    );

    push @element,    $element->{element};
    push @element_id, $element->{id};

  }

  $html->tpl_show(
    _include("timetracker_add_form", "Timetracker"),
    {
      ADMIN      => $admin->{AID},
      DATEPICKER => $html->form_datepicker("DATE", $date_for_picker),
      FORM_GROUP => $form_group,
      BTN        => $btn_value,
      ACTION     => $btn_action
    }
  );

  my $table = $html->table(
    {
      width   => "100%",
      caption => $lang{ALL_FILLING},
      title   => [ $lang{DATE}, @element, "" ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      export  => 1
    }
  );

  foreach my $item (@$Timetracker_list) {
    $hash{ $item->{date} }->{ $item->{element_id} } = $item->{time_per_element};
  }

  foreach my $date (reverse sort keys %hash) {
    @num_element = ();
    foreach my $item (@element_id) {
      push @num_element, ($hash{$date}->{$item} || 0);
    }
    my $del_button  = $html->button("", "index=$index&DELETE=$date&NAME=$admin->{AID}", { class => "text-danger", ADD_ICON => "glyphicon glyphicon-trash" });
    my $edit_button = $html->button("", "index=$index&EDIT=$date&NAME=$admin->{AID}",   { class => "",            ADD_ICON => "glyphicon glyphicon-pencil" });
    $table->addrow($date, @num_element, "$edit_button$del_button");
  }

  print $table->show();

}

#**********************************************************

=head2 add_item() - Setting the number of elements and priority.

=cut

#**********************************************************

sub add_item {

  my $btn_action = 'ADD';
  my $btn_value  = $lang{ADD};

  if ($FORM{ADD}) {
    $Timetracker->add_element(
      {
        ELEMENT  => $FORM{ELEMENT},
        PRIORITY => $FORM{PRIORITY},
      }
    );

    $html->message("info", $lang{ADD_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{DELETE}) {
    $Timetracker->del_element($FORM{DELETE});

    $html->message("info", $lang{DELETE_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{CHANGE}) {
    $Timetracker->change_element(
      {
        ID       => $FORM{ID},
        ELEMENT  => $FORM{ELEMENT},
        PRIORITY => $FORM{PRIORITY},
      }
    );

    $html->message("info", $lang{CHANGE_MASSAGE}, $lang{OPERATION});
  }

  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1, DESC => "desc" });

  if($Timetracker->{errno}){
    $html->message("err", $lang{ERROR}, $lang{NOTABLES});
    return 1;
  }

  if ($FORM{EDIT}) {
    $btn_action = 'CHANGE';
    $btn_value  = $lang{CHANGE};
    foreach my $item (@$Timetracker_list_element) {
      if ($item->{id} == $FORM{EDIT}) {

        $html->tpl_show(
          _include("timetracker_add_item_form", "Timetracker"),
          {
            FORM_NAME => "EDIT_ITEM",
            TITLE     => $lang{EDIT_ITEM},
            BTN       => $btn_value,
            ACTION    => $btn_action,
            ID        => $item->{id},
            PRIORITY  => $item->{priority},
            ELEMENT   => $item->{element}
          }
        );
        last;
      }

    }
  }
  else {
    $html->tpl_show(
      _include("timetracker_add_item_form", "Timetracker"),
      {
        FORM_NAME => "ADD_ITEM",
        TITLE     => $lang{ADD_ITEM},
        BTN       => $btn_value,
        ACTION    => $btn_action
      }
    );
  }

  my $table = $html->table(
    {
      width   => "100%",
      caption => "$lang{ELEMENTS}",
      title   => [ "ID", "$lang{ELEMENT}", $lang{PRIORITY}, "" ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      export  => 1
    }
  );

  foreach my $item (@$Timetracker_list_element) {
    my $del_button  = $html->button("", "index=$index&DELETE=$item->{id}", { class => "text-danger", ADD_ICON => "glyphicon glyphicon-trash" });
    my $edit_button = $html->button("", "index=$index&EDIT=$item->{id}",   { class => "",            ADD_ICON => "glyphicon glyphicon-pencil" });
    $table->addrow($item->{id}, $item->{element}, $item->{priority}, "$edit_button$del_button");
  }

  print $table->show();

}