#!perl

=head1 NAME

  Timetracker

=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use Timetracker::db::Timetracker;
use Admins;

our ($html, %FORM, $db, %conf, $admin, %lang, @WEEKDAYS);
my $Timetracker = Timetracker->new($db, $admin, \%conf);
my $Admins = Admins->new($db, \%conf);


#**********************************************************
=head2 timetracker() - Accounting and time allocation. Report.

=cut
#**********************************************************
sub timetracker {

  reports(
    { 
      DATE        => $FORM{FROM_DATE_TO_DATE}, 
      PERIOD_FORM => 1, 
      NO_GROUP    => 1, 
      NO_TAGS     => 1, 
      DATE_RANGE  => 1 
    }
  );

  my %hash             = ();
  my @element          = ();
  my $Timetracker_list = $Timetracker->list_for_timetracker(
    { 
      COLS_NAME => 1, 
      DATE => $FORM{FROM_DATE_TO_DATE}
    }
  );
  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1 });
  my $Admin_name;
  my @priority = ();

  foreach my $element (@$Timetracker_list_element) {

    push @element, $element->{element};

    if ($element->{priority} == 1) {
      push @priority, $element->{element};
    }

    foreach my $item (@$Timetracker_list) {

      $Admin_name = $Admins->info($item->{aid});

      if ($element->{id} == $item->{element_id}) {

        $hash{ $Admin_name->{A_FIO} }->{ $element->{element} } += $item->{time_per_element};
      }
      else {
        $hash{ $Admin_name->{A_FIO} }->{ $element->{element} } += 0;
      }
    }
  }

  my $table = $html->table(
    {
      width   => "100%",
      caption => $lang{TIMETRACKER},
      title   => [ $lang{NAME}, @element, $lang{COEFFICIENT} ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      MENU    => "$lang{ADD}:index=" . get_function_index('add_time') . "&add_form=1&$pages_qs:add",
      export  => 1,
    }
  );

  my $coefficient;
  my @num_element;
  my $sum_num_element;

  foreach my $name (sort keys %hash) {
    @num_element     = ();
    $coefficient     = 0;
    $sum_num_element = 0;

    foreach my $item (@element) {
      $sum_num_element += $hash{$name}->{$item};
      push @num_element, sprintf('%.2f', ($hash{$name}->{$item})/100);
      foreach my $element (@priority) {
        if ($element eq $item) {
          $coefficient += $hash{$name}->{$item};
        }
      }
    }

    $coefficient = ($coefficient) ? sprintf('%0.1f', (($coefficient * 100) / $sum_num_element)) : 0;
    $table->addrow($name, @num_element, "$coefficient");
  }

  print $table->show();
  return 1;
}


#**********************************************************
=head2 add_time() - Filling out a report.

=cut
#**********************************************************
sub add_time {

  my $date_for_picker = $DATE;
  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1 });
  my $form_group;
  my @element;
  my @num_element;
  my @element_id;
  my %hash;
  my $btn_action = 'ADD';
  my $btn_value  = $lang{ADD};
  my %hash1;
  my $support_time;
  my ($year, undef, undef) = split('-', $DATE);

  if ($FORM{ADD}) {
    $Timetracker->del(
      {
        AID  => $admin->{AID},
        DATE => $FORM{DATE},
      }
    );

    foreach my $element (@$Timetracker_list_element) {
      $Timetracker->add(
        {
          AID              => $admin->{AID},
          ELEMENT_ID       => $element->{id},
          TIME_PER_ELEMENT => (sprintf('%.2f', $FORM{ $element->{id} })) * 100,
          DATE             => $FORM{DATE},
        }
      );
    }

    $html->message("info", $lang{ADD_MASSAGE}, $lang{OPERATION});
    $date_for_picker = $FORM{DATE};
  }

  if ($FORM{DELETE}) {

    $Timetracker->del(
      {
        AID  => $admin->{AID},
        DATE => $FORM{DELETE},
      }
    );

    $html->message("info", $lang{DELETE_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{CHANGE}) {
    $Timetracker->del(
      {
        AID  => $admin->{AID},
        DATE => $FORM{DATE},
      }
    );

    foreach my $element (@$Timetracker_list_element) {

      $Timetracker->add(
        {
          AID              => $admin->{AID},
          ELEMENT_ID       => $element->{id},
          TIME_PER_ELEMENT => $FORM{ $element->{id} },
          DATE             => $FORM{DATE},
        }
      );
    }

    $html->message("info", $lang{CHANGE_MASSAGE}, $lang{OPERATION});
  }

  my $Timetracker_list = $Timetracker->list_for_timetracker(
    {
      COLS_NAME => 1,
      DESC      => "desc",
      DATE      => ">=$year-01-01",
      AID       => $admin->{AID}
    }
  );

  my $Timetracker_list_element_ = $Timetracker->list_element({ COLS_NAME => 1, DESC => "desc" });

  my $datepicker = $html->form_datepicker("DATE", $date_for_picker);
  my $datepicker_form = $html->tpl_show(
      _include("timetracker_datepicker_form", "Timetracker"),
      {
        DATEPICKER  => $datepicker,
      },
      { OUTPUT2RETURN => 1 }
    );

  if($Timetracker->{errno}){
    $html->message("err", $lang{ERROR}, $lang{NOTABLES});
    return 1;
  }

  if ($FORM{EDIT}) {
    $btn_action      = 'CHANGE';
    $btn_value       = $lang{CHANGE};
    foreach my $element (@$Timetracker_list_element_) {
      foreach my $item (@$Timetracker_list) {
        if ($item->{aid} eq $FORM{NAME} && $item->{date} eq $FORM{EDIT}) {
          $hash1{ $item->{element_id} } = $item->{time_per_element};
        }
      }
    }
    $datepicker_form = "<input type='hidden' name='DATE' value='$FORM{EDIT}'>";
  }

  require Msgs;
  our $Msgs = Msgs->new($db, $admin, \%conf);
  my $messages_reply_list = $Msgs->messages_reply_list(
    { 
      COLS_NAME => 1, 
      AID       => $admin->{AID},
      DATETIME  => ">$DATE",
    }
  );
  foreach my $data (@$messages_reply_list){
    $support_time += time2sec($data->{run_time}); 
  }
  $support_time = sprintf('%.2f',$support_time / 3600);

  foreach my $element (@$Timetracker_list_element) {
    my $num_element = '';
    if($hash1{ $element->{id} }){
      $num_element = $hash1{ $element->{id} };
    }
    elsif($element->{element} =~ /^support$/i){
      $num_element = $support_time;
    }
    $form_group .= $html->tpl_show(
      _include("timetracker_add_form_group", "Timetracker"),
      {
        ELEMENT     => $element->{element},
        ID          => $element->{id},
        NUM_ELEMENT => $num_element
      },
      { OUTPUT2RETURN => 1 }
    );

    push @element,    $element->{element};
    push @element_id, $element->{id};
  }

  $html->tpl_show(
    _include("timetracker_add_form", "Timetracker"),
    {
      ADMIN      => $admin->{AID},
      DATEPICKER => $datepicker_form,
      FORM_GROUP => $form_group,
      BTN        => $btn_value,
      ACTION     => $btn_action
    }
  );

  my %dates  = ();
  my $tables = '';
  my $count  = 0;
  foreach my $item (@$Timetracker_list) {
    my $d = Time::Piece->strptime($item->{date}, "%Y-%m-%d");
    $dates{$item->{date}} = 1;
    $hash{$d->week}->{ $item->{date} }->{ $item->{element_id} } = $item->{time_per_element};
  }

  my %tables = ();
  foreach my $week (reverse sort {$a <=> $b} keys %hash) {

    $tables{$week} = $html->table(
      {
        width   => "100%",
        caption => $lang{WEEK} . ": " . $week,
        title   => [ $lang{DATE}, @element, "" ],
        qs      => $pages_qs,
        ID      => "TABLE_ID",
        export  => 1
      }
    );

    foreach my $date (sort keys %{$hash{$week}}){
      @num_element = ();
      my $d = Time::Piece->strptime($date, "%Y-%m-%d");
      $d->day_list(@WEEKDAYS);
      foreach my $item (@element_id) {
        push @num_element, sprintf('%.2f', ($hash{$week}->{$date}->{$item})/100);
      }
      my $del_button  = $html->button("", "index=$index&DELETE=$date&NAME=$admin->{AID}", 
        { class => "text-danger", ADD_ICON => "glyphicon glyphicon-trash" });
      my $edit_button = $html->button("", "index=$index&EDIT=$date&NAME=$admin->{AID}",   
        { class => "",            ADD_ICON => "glyphicon glyphicon-pencil" });
      $tables{$week}->addrow($d->wdayname . " " . $d->dmy, @num_element, "$edit_button$del_button");
    }

    $tables .= $html->element('div', $tables{$week}->show(), { class => "col-md-4" });
    $count++;
    if($count==3){
      print $html->element('div', $tables, { class => "row" });
      $tables = '';
      $count  = 0;
    }
  }

  $html->element('div', $tables, { class => "row" });
  
  return 1;
}

#**********************************************************
=head2 add_item() - Setting the number of elements and priority.

=cut
#**********************************************************
sub add_item {

  my $btn_action = 'ADD';
  my $btn_value  = $lang{ADD};

  if ($FORM{ADD}) {
    $Timetracker->add_element(
      {
        ELEMENT  => $FORM{ELEMENT},
        PRIORITY => $FORM{PRIORITY},
      }
    );

    $html->message("info", $lang{ADD_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{DELETE}) {
    $Timetracker->del_element($FORM{DELETE});
    $html->message("info", $lang{DELETE_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{CHANGE}) {
    $Timetracker->change_element(
      {
        ID       => $FORM{ID},
        ELEMENT  => $FORM{ELEMENT},
        PRIORITY => $FORM{PRIORITY},
      }
    );

    $html->message("info", $lang{CHANGE_MASSAGE}, $lang{OPERATION});
  }

  my $Timetracker_list_element = $Timetracker->list_element({ COLS_NAME => 1, DESC => "desc" });

  if($Timetracker->{errno}){
    $html->message("err", $lang{ERROR}, $lang{NOTABLES});
    return 1;
  }

  if ($FORM{EDIT}) {
    $btn_action = 'CHANGE';
    $btn_value  = $lang{CHANGE};
    foreach my $item (@$Timetracker_list_element) {
      if ($item->{id} == $FORM{EDIT}) {

        $html->tpl_show(
          _include("timetracker_add_item_form", "Timetracker"),
          {
            FORM_NAME => "EDIT_ITEM",
            TITLE     => $lang{EDIT_ITEM},
            BTN       => $btn_value,
            ACTION    => $btn_action,
            ID        => $item->{id},
            PRIORITY  => $item->{priority},
            ELEMENT   => $item->{element}
          }
        );
        last;
      }
    }
  }
  else {
    $html->tpl_show(
      _include("timetracker_add_item_form", "Timetracker"),
      {
        FORM_NAME => "ADD_ITEM",
        TITLE     => $lang{ADD_ITEM},
        BTN       => $btn_value,
        ACTION    => $btn_action
      }
    );
  }

  my $table = $html->table(
    {
      width   => "100%",
      caption => "$lang{ELEMENTS}",
      title   => [ "ID", "$lang{ELEMENT}", $lang{PRIORITY}, "" ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      export  => 1
    }
  );

  foreach my $item (@$Timetracker_list_element) {
    my $del_button  = $html->button("", "index=$index&DELETE=$item->{id}", { class => "text-danger", ADD_ICON => "glyphicon glyphicon-trash" });
    my $edit_button = $html->button("", "index=$index&EDIT=$item->{id}",   { class => "",            ADD_ICON => "glyphicon glyphicon-pencil" });
    $table->addrow($item->{id}, $item->{element}, $item->{priority}, "$edit_button$del_button");
  }

  print $table->show();
  return 1;
}

sub decomposition {
  my %hash = (
    html          => 1,
    perl          => 1,
    sql           => 1,
    "service api" => 2,
  );

  my $checkboxes;
  my $totalcount;
  my $label_color;
  my $checked = '';

  my @SwitchOptionCheck = split ", ", $FORM{"SwitchOption"} // "";
  my $balcount;

  my $count = 0;

  foreach my $value (sort {$hash{$a} <=> $hash{$b} or $a cmp $b} keys %hash) {
    $checked = '';
    if ($hash{$value} == 1) {
      $label_color = "label-success";
    }
    elsif ($hash{$value} == 2) {
      $label_color = "label-warning";
    }
    elsif ($hash{$value} > 2) {
      $label_color = "label-danger";
    }
    else {
      $label_color = "label-default";
    }
    for (@SwitchOptionCheck) {
      if ($_ == $count) {
        $balcount += $hash{$value};
        $checked = 'checked';
      }
    }

    $checkboxes .= $html->tpl_show(_include("timetracker_decomposition_chekbox", "Timetracker"),
      { NAME => $value, ID => $count, DIFFICULT => $count, LABEL_COLOR => $label_color, CHECKED => $checked },
      { OUTPUT2RETURN => 1 });
    $totalcount += $hash{$value};
    $count++;
  }

  my $percentbal = ($balcount > 0) ? int(($balcount * 100) / $totalcount) : 0;

  my $fibonacci = fibonacci($balcount);

  if ($percentbal == 0) {
    $fibonacci = fibonacci($totalcount);
    $html->message("info", "$lang{FIBONACHI} $fibonacci", "");
  }
  elsif ($percentbal < 40) {
    $html->message("info", "$lang{FIBONACHI} $fibonacci",
      "<strong>$percentbal%</strong> $lang{YOUR_FINAL_SCORE}. $lang{YOURFINAL_SUM} <strong>$balcount</strong>");
  }
  elsif ($percentbal < 80) {
    $html->message("info", "$lang{FIBONACHI} $fibonacci",
      "<strong>$percentbal%</strong> $lang{YOUR_FINAL_SCORE}. $lang{YOURFINAL_SUM} </strong>$balcount</strong>");
  }
  elsif ($percentbal >= 80) {
    $html->message("info", "$lang{FIBONACHI} $fibonacci",
      "<strong>$percentbal%</strong> $lang{YOUR_FINAL_SCORE}. $lang{YOURFINAL_SUM} </strong>$balcount</strong>");
  }

  $html->tpl_show(_include("timetracker_decomposition_form", "Timetracker"), { CHECKBOXES => $checkboxes });

  return 1;
}

#**********************************************************
=head2 fibonacci($attr)
 
  Arguments:
    $attr   - Extra attributes
 
  Returns:
   TRUE or FALSE
 
  Example:
 
    fibonacci({ ATTR => 13 });
 
=cut
#**********************************************************
sub fibonacci {
  my ($n) = @_;
  if ($n < 3) {
    return 1;
  }
  else {
    return fibonacci($n - 1) + fibonacci($n - 2);
  }
}

1;